config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :settings, only: [:index] do
    collection do
      get :password
      patch :update_user
      patch :update_password
    end
  end

  namespace :admin do
    root to: 'home#index'
    resources :categories
    resources :products
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, :position, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
    attachable.variant :big_thumb, resize_to_limit: [600, 700]
  end
  belongs_to :category

  validates :name, :description, :price, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  validates :name, :phone, presence: true

  enum role: { user: 'user', admin: 'admin' }
end

app/controllers/admin/base_controller.rb
# frozen_string_literal: true

module Admin
  # Base Contrller Admin
  class BaseController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
    before_action :only_admin!

    private

    def only_admin!
      redirect_to root_path unless current_user.admin?
    end
  end
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  # Categories Controller Admin
  class CategoriesController < BaseController
    before_action :set_category, only: %i[show edit update destroy]

    def index
      @categories = Category.all
    end

    def show; end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      return redirect_to admin_categories_path(@category), notice: 'Categoria criada com sucesso!' if @category.save

      render :new, status: :unprocessable_entity
    end

    def edit; end

    def update
      category_update = @category.update(category_params)
      return redirect_to admin_categories_path(@category), notice: 'Categoria atualizada!' if category_update

      render :edit, status: :unprocessable_entity
    end

    def destroy
      return redirect_to admin_categories_path, notice: 'Categoria excluída com sucesso.' if @category.destroy
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :position)
    end
  end
end

app/controllers/admin/home_controller.rb
# frozen_string_literal: true

module Admin
  # Home Controller Admin
  class HomeController < BaseController
    def index; end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

module Admin
  # Products Controller Admin
  class ProductsController < BaseController
    before_action :set_product, only: %i[show edit update destroy]

    def index
      @products = Product.all
    end

    def edit; end

    def new
      @product = Product.new
      authorize @product
    rescue Pundit::NotAuthorizedError
      flash[:notice] = 'Você só pode cadastrar um produto se tiver uma categoria criada.'
      redirect_to action: :index
    end

    def show; end

    def create
      @product = Product.new(product_params)
      return redirect_to admin_products_path(@product), notice: 'Produto criado com sucesso!' if @product.save

      render :new, status: :unprocessable_entity
    end

    def update
      product_update = @product.update(product_params)
      return redirect_to admin_products_path(@product), notice: 'Produto atualizado!' if product_update

      render :edit, status: :unprocessable_entity
    end

    def destroy
      return redirect_to admin_products_path, notice: 'Produto excluído com sucesso.' if @product.destroy
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :publish, :image, :category_id, :promo, :promo_price)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Class Application COntroller
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :phone)
    end
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# class users
class HomeController < ApplicationController
  def index
    @products = Product.all.map { |product| ProductPresenter.new(product) }
  end
end

app/controllers/settings_controller.rb
# frozen_string_literal: true

# class users
class SettingsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def password; end

  def update_user
    if current_user.update(user_params)
      redirect_to settings_path, notice: 'Seus dados foram atualizado com sucesso.'
    else
      render :index
    end
  end

  def update_password
    if !current_password_params[:current_password].empty? && current_user.valid_password?(current_password_params[:current_password])
      if current_user.update(password_params)
        bypass_sign_in(current_user)
        redirect_to password_settings_path, notice: 'Sua senha foi atualizada com sucesso'
      else
        render :password
      end
    else
      redirect_to password_settings_path, notice: 'Você precisa informar sua senha atual para trocar de senhas'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :phone, :avatar)
  end

  def current_password_params
    params.require(:user).permit(:current_password)
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_helper.rb
module UserHelper
  def user_avatar_url(current_user)
    return current_user.avatar if current_user.avatar.attached?

    'profile'
  end
end

app/views/admin/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= category.position %>
  </p>

</div>

app/views/admin/categories/_form.html.erb
<%= simple_form_for([:admin, @category]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/categories/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button
            type="button"
              class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                style="background: none; border: none;">
          x
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/categories/form", category: @category %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editar categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/categories/form_modal", locals: { category: @category }%>
<% end %>

app/views/admin/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Posição</th>
            <th>Ações</th>
          </thead>
          <tbody>
            <% @categories.each do |category| %>
              <tr>
                  <td><%= category.name %></td>
                  <td><%= category.position %></td>
                  <td>
                    <%= link_to "Detalhes", admin_category_path(category), class: 'btn btn-dark' %>
                    <%= link_to "Editar", edit_admin_category_path(category), data: { controller: 'admin-modal' }, class: 'btn btn-warning' %>
                    <%= link_to "Excluir", admin_category_path(category), data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?'}, class: "btn btn-danger" %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to "Nova categoria", new_admin_category_path, data: { controller: 'admin-modal' }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<h1 class="h3 mb-4 text-gray-800">Nova categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", category: @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/categories/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/categories/form_modal", locals: { category: @category }%>
<% end %>

app/views/admin/categories/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes da categoria</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @category %>
      </div>
    </div>
  </div>
</div>

app/views/admin/home/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>

<div class="row">
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
              Earnings (Monthly)</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                  Earnings (Annual)</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
            </div>
              <div class="col-auto">
                <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
              </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-info shadow h-100 py-2">
        <div class="card-body">
          <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                </div>
                <div class="row no-gutters align-items-center">
                  <div class="col-auto">
                    <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                  </div>
                  <div class="col">
                    <div class="progress progress-sm mr-2">
                      <div class="progress-bar bg-info" role="progressbar"
                        style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                        aria-valuemax="100"></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-auto">
                <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
              </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                  Pending Requests</div>
                <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
              </div>
              <div class="col-auto">
                <i class="fas fa-comments fa-2x text-gray-300"></i>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/admin/products/_form.html.erb
<%= simple_form_for([:admin, @product]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :publish %>
    <%= f.input :promo %>
    <%= f.input :promo_price %>
    <%= f.association :category, include_blank: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Salvar', class: 'btn btn-info' %>
  </div>
<% end %>

app/views/admin/products/_form_modal.html.erb
<%= turbo_frame_tag :bootstrap_modal, target: :_top do %>
  <div class="modal fade" id="staticBackdrop" data-controller="modal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
          <button
            type="button"
              class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
                style="background: none; border: none;">
          x
          </button>
        </div>
        <div class="modal-body">
          <%= render "admin/products/form", product: @product %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Imagem:</strong>
    <%= image_tag product.image.variant(:thumb) %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Preço:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Ativo:</strong>
    <%= product.publish %>
  </p>

  <p>
    <strong>Promoção:</strong>
    <%= product.promo %>
  </p>

  <p>
    <strong>Preço Promoção:</strong>
    <%= product.promo_price %>
  </p>

</div>

app/views/admin/products/edit.html.erb
<h1 class="h3 mb-4 text-gray-800">Editar produto</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/edit.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/products/form_modal", locals: { product: @product }%>
<% end %>

app/views/admin/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="h3 mb-4 text-gray-800">Produtos</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <table class="table table-striped">
          <thead>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Ativo</th>
            <th>Promoção</th>
            <th>Promo Price</th>
          </thead>
          <tbody>
            <% @products.each do |product| %>
              <tr>
                  <td><%= product.name %></td>
                  <td><%= product.description %></td>
                  <td><%= product.price %></td>
                  <td><%= product.publish %></td>
                  <td><%= product.promo %></td>
                  <td><%= product.promo_price %></td>
                  <td>
                    <%= link_to "Detalhes", admin_product_path(product), class: 'btn btn-dark' %>
                    <%= link_to "Editar", edit_admin_product_path(product), data: { controller: 'admin-modal' },  class: 'btn btn-warning' %>
                    <%= link_to "Excluir", admin_product_path(product), data: { turbo_method: :delete, turbo_confirm: 'Deseja realmente excluir?'}, class: "btn btn-danger" %>
                  </td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <%= link_to "Novo produto", new_admin_product_path, data: { controller: 'admin-modal' }, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<h1 class="h3 mb-4 text-gray-800">Novo produto</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render "form", product: @product %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.turbo_stream.erb
<%= turbo_stream.replace "bootstrap_modal" do %>
  <%= render partial: "admin/products/form_modal", locals: { product: @product }%>
<% end %>

app/views/admin/products/show.html.erb
<h1 class="h3 mb-4 text-gray-800">Detalhes do Produto</h1>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-body">
        <%= render @product %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<header class="bg-dark py-5">
  <div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
      <h1 class="display-4 fw-bolder">Sua loja virtual preferida</h1>
      <p class="lead fw-normal text-white-50 mb-0">Aqui vai ser o slogan</p>
    </div>
  </div>
</header>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
      <% @products.each do |product| %>
        <div class="col mb-5">
          <div class="card h-100">
            <% if product.promo? %>
              <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Promo</div>
            <% end %>
            <!-- Product image-->
            <%= image_tag product.image.variant(:thumb), class: 'card-img-top' %>
            <!-- Product details-->
            <div class="card-body p-4">
              <div class="text-center">
                <!-- Product name-->
                <h5 class="fw-bolder"><%= product.name %></h5>
                <!-- Product price-->
                <%= product.price %>
              </div>
            </div>
            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
              <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Adicionar no carrinho</a></div>
            </div>
          </div>
        </div>
      <% end %>
      <!-- <div class="col mb-5">
        <div class="card h-100">
          <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
          <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
          <div class="card-body p-4">
            <div class="text-center">
              <h5 class="fw-bolder">Special Item</h5>
              <div class="d-flex justify-content-center small text-warning mb-2">
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
                <div class="bi-star-fill"></div>
              </div>
              <span class="text-muted text-decoration-line-through">$20.00</span>
              $18.00
            </div>
          </div>
          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
          </div>
        </div>
      </div> -->
    </div>
  </div>
</section>
<!-- Footer-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loja Cezzar - Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>
  </head>

  <body id="page-top">
    <div id="wrapper">
      <%= render 'layouts/admin/sidebar' %>
      <div id="content-wrapper" class="d-flex flex-column">

          <div id="content">
            <%= render 'layouts/admin/topbar' %>
            <div class="container-fluid">
              <%= yield %>
            </div>
        </div>
        <%= render 'layouts/admin/footer'%>
      </div>
    </div>
    <%= turbo_frame_tag "bootstrap_modal" %>

    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>
  </body>
</html>

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
      <div class="copyright text-center my-auto">
          <span>Todos os direitos reservados &copy; Your Website <%= Date.current.year %></span>
      </div>
  </div>
</footer>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_root_path %>">
      <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-3">Progadmin</div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
      <a class="nav-link" href="<%= admin_root_path %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
      <a class="nav-link" href="<%= admin_categories_path %>">
          <i class="fas fa-fw fa-bookmark"></i>
          <span>Categorias</span>
      </a>
  </li>

  <li class="nav-item">
      <a class="nav-link" href="<%= admin_products_path %>">
          <i class="fas fa-fw fa-puzzle-piece"></i>
          <span>Produtos</span>
      </a>
  </li>

	<li class="nav-item">
		<a class="nav-link collapsed" data-method="delete" href="<%= destroy_user_session_path %>">
			<i class="fas fa-arrow-alt-circle-left"></i>
			<span>Sair</span>
		</a>
	</li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bem vindo ao Ecommerce Cezzar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <!-- Navigation-->
    <%= render 'layouts/store/nav' %>
    <%= yield %>
    <%= render 'layouts/store/footer' %>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<div class="alert alert-info text-center">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
</div>

app/views/layouts/store/_footer.html.erb
<footer class="py-5 bg-dark">
  <div class="container"><p class="m-0 text-center text-white">Loja Cezzar &copy; Your Website 2022</p></div>
</footer>

app/views/layouts/store/_user_signed_in.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to "Meu Perfil", settings_path, class: "nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "nav-link"  %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to "Cadastre-se", new_user_registration_path, method: :delete, class: "nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Entrar", new_user_session_path, method: :delete, class: "nav-link"  %>
  </li>
<% end %>

app/views/settings/index.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <div class="card-header">
            Meu Perfil
          </div>

          <ul class="list-group list-group-flush">
            <a href="#" class="menu-item-profile"><li class="list-group-item">Alterar senha</li></a>
            <a href="#" class="menu-item-profile"><li class="list-group-item">Endereços</li></a>
            <a href="#" class="menu-item-profile"><li class="list-group-item">Produtos favoritos</li></a>
          </ul>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2><%= current_user.name %></h2>
            <%= image_tag user_avatar_url(current_user), width: 120, height: 120, class: 'mb-4 rounded-circle' %>
            <%= simple_form_for current_user, url: update_user_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :avatar, label: false, hint: 'Escolha uma foto para sua conta.', input_html:{ class: 'input_image_full'} %>
              <%= f.input :email, readonly: true %>
              <%= f.input :name %>
              <%= f.input :phone, input_html: { class: 'mask-phone' } %>
              <%= f.button :submit, "Atualizar", class: 'btn btn-primary mt-4' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/settings/password.html.erb
<section class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <div class="card">
          <%= render 'menu'%>
        </div>
      </div>
      <div class="col-9">
        <div class="card">
          <div class="card-body">
            <%= render 'layouts/shared/flash' if flash.present? %>
            <h2>Alterar Senha</h2>
            <%= image_tag user_avatar_url(current_user), width: 120, height: 120, class: 'mb-4 rounded-circle' %>
            <%= simple_form_for current_user, url: update_password_settings_path, data: { turbo: false } do |f| %>
              <%= f.input :current_password %>
              <%= f.input :password %>
              <%= f.input :password_confirmation %>
              <%= f.button :submit, "Atualizar Senha", class: 'btn btn-primary mt-4' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>